version: "3"
services: 
  db: 
    image: mongo:4.2
    container_name: db
    restart: always
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=wasitt-d
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=root
  app: 
    build: .
    command: yarn dev
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/app