version: "3"



services: 
  mongo:
    hostname: mongo
    container_name: localmongo1
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=wasitt-d
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - 27017:27017
    # restart: always
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]}).ok || rs.status().ok || rs.secondaryOk().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes: 
      - ./mongo-initdb.d:/docker-entrypoint-initdb.d
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo:latest
    depends_on:
      - mongo
    volumes: 
      - ./mongo-initdb.d:/docker-entrypoint-initdb.d
    restart: "no"
  # mongo:
  #   hostname: mongo
  #   container_name: mongo
  #   image: mongo:latest
  #   ports: 
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_DATABASE=wasitt-d
  #     - MONGO_REPLICA_SET_NAME=rs0
  #     # - MONGO_INITDB_ROOT_USERNAME=root
  #     # - MONGO_INITDB_ROOT_PASSWORD=root
  #   restart: always
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]


  # mongosetup:
  #   image: mongo:latest
  #   restart: "no"
  #   # restart: on-failure
  #   container_name: mongosetup
  #   depends_on:
  #     - mongo
  #   volumes: 
  #     - ./mongo-initdb.d:/docker-entrypoint-initdb.d
  
  app: 
    container_name: app
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:api.wasitt.com,www.api.wasitt.com
      - traefik.webservice.frontend.entryPoints=http,https
    build: .
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
      - mongosetup
    links:
      - mongo
      - mongosetup
    command: yarn dev

    # logging: 
    #   driver: "json-file"
    #   options: 
    #     max-size: "10m"
    #     max-file: "5"
  traefik: 
    image: traefik:v1.7.6
    command: --api --docker.exposedbydefault=false 
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
