version: "3"

services: 
  app: 
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:wasitt.com"
    
  reverse-proxy: 
    image: traefik:latest
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
